# Generated by Django 5.2.12 on 2026-03-25 03:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FIAT', 'Fiat Currency'), ('CRYPTO', 'Cryptocurrency')], max_length=10)),
                ('current_price_usd', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=24)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
